name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl software-properties-common lsb-release
          sudo apt-get install -y build-essential cmake


      - name: Configure
        shell: bash
        run: |
          cd build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release -- -j