name: Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libx11-dev libxtst-dev ca-certificates gpg wget

      - name: Add Kitware APT repository and install CMake 4
        run: |
          # Voeg de Kitware GPG-sleutel toe
          curl -fsSL https://apt.kitware.com/keys/kitware-archive-latest.asc | \
            gpg --dearmor | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg > /dev/null

          # Voeg de repository toe met keyring-verificatie
          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main" | \
            sudo tee /etc/apt/sources.list.d/kitware.list > /dev/null

          # Update en installeer CMake
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure
        run: |
          cmake --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -- -j$(nproc)
