name: Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libx11-dev libxtst-dev ca-certificates gpg wget

      - name: Remove system CMake
        run: |
          sudo apt-get remove -y cmake || true

      - name: Add Kitware APT repository and install CMake 4
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.sh
          chmod +x cmake-4.1.2-linux-x86_64.sh
          sudo ./cmake-4.1.2-linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Configure
        run: |
          cmake --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -- -j$(nproc)


